In [2]:
import pandas as pd
import numpy as np      
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Q1. Pandas version
pd.__version__

'2.1.4'

In [7]:
df = pd.read_csv(r"C:\Users\Jotman\Desktop\ml-zoomcamp 2025\datasets\car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [ ]:
# Q2. Records count
len(df)

9704

In [ ]:
# Q3. Fuel types
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [ ]:
# Q4. Missing values
df.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
# Q5. Max fuel efficiency
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

In [ ]:
# Q6. Median value of horsepower
df['horsepower'].median()

149.0

In [22]:
df["horsepower"].mode()

0    152.0
Name: horsepower, dtype: float64

In [23]:
df["horsepower"].fillna(152, inplace=True)

In [24]:
df['horsepower'].median()

152.0

In [ ]:
# Q7. Sum of weights
asia_cars = df[df['origin'] == 'Asia']
asia_cars.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [30]:
df_selected = asia_cars[['vehicle_weight', 'model_year']]
df_selected.head()


vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016

In [31]:
df_selected.head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [34]:
df_selected.to_numpy()

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]])

In [35]:
x = df_selected.to_numpy()

In [36]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       ...,
       [2545.07013932, 2012.        ],
       [3107.42781965, 2005.        ],
       [2908.04347736, 2005.        ]])

In [37]:
x.T

array([[2714.21930965, 2783.86897424, 3582.68736772, ..., 2545.07013932,
        3107.42781965, 2908.04347736],
       [2016.        , 2010.        , 2007.        , ..., 2012.        ,
        2005.        , 2005.        ]])

In [38]:
x @ x.T

array([[11431242.46085133, 11608190.92541486, 13770311.23387465, ...,
        10964070.51655377, 12476320.5914294 , 11935147.75952883],
       [11608190.92541486, 11790026.46575708, 14007802.20739725, ...,
        11129261.79813728, 12680721.8968322 , 12125662.01236453],
       [13770311.23387465, 14007802.20739725, 16863697.77478558, ...,
        13156274.6381037 , 15156977.39555511, 14442645.63109125],
       ...,
       [10964070.51655377, 11129261.79813728, 13156274.6381037 , ...,
        10525526.01407672, 11942681.75390073, 11435234.61807464],
       [12476320.5914294 , 12680721.8968322 , 15156977.39555511, ...,
        11942681.75390073, 13676132.65434947, 13056560.20229596],
       [11935147.75952883, 12125662.01236453, 14442645.63109125, ...,
        11435234.61807464, 13056560.20229596, 12476741.86619525]])

In [42]:
XTX = x.T @ x
XTX

array([[3.01651358e+10, 1.96349896e+10],
       [1.96349896e+10, 1.31377985e+10]])

In [43]:
np.linalg.inv(XTX)

array([[ 1.21977675e-09, -1.82300740e-09],
       [-1.82300740e-09,  2.80067709e-09]])

In [ ]:
# Create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Compute w
w = XTX_inv @ X.T @ y

# Calculate the sum of the elements of w
w = w.sum()

print(w)


0.5187709081074007
